# version: '3.8'

services:
  uce-rag-service:
    build:
      context: .
      dockerfile: ./rag/Dockerfile
    ports:
      - "8080:5678" 
    depends_on:
      - uce-postgresql-db 

  uce-web:
    build:
      context: .
      dockerfile: ./uce.portal/uce.web/Dockerfile
    ports:
      - "8008:4567"
    depends_on:
      - uce-postgresql-db

  uce-postgresql-db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: uce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234 
    ports:
      - "8002:5432"
    #volumes:
    #  - pgdata:/var/lib/uce-gerparcor-eval/data 

volumes:
  pgdata:
