# version: '3.8'

services:
  biofid-rag-service:
    build:
      context: .
      dockerfile: ./rag/Dockerfile
    ports:
      - "8080:5678" 
    depends_on:
      - biofid-postgresql-db 

  biofid-web:
    build:
      context: .
      dockerfile: ./uce.portal/uce.web/Dockerfile
    ports:
      - "8008:4567"
    depends_on:
      - biofid-postgresql-db

  biofid-postgresql-db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: biofid
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234 
    ports:
      - "8002:5432"
    volumes:
      - pgdata:/var/lib/biofid-postgresql-db/data 

volumes:
  pgdata:
